# Generated by Django 5.2.4 on 2025-07-31 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='auction_id',
            new_name='auction',
        ),
    ]
