# Generated by Django 5.2.4 on 2025-07-30 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='sold_by',
        ),
    ]
