# Generated by Django 5.2.4 on 2025-07-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_auctions_sold_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='auction_id',
            new_name='auction',
        ),
    ]
