# Generated by Django 5.2.4 on 2025-07-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctions_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='item_category',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
